### PR TITLE
Fix footnotes: nested, confused for link refs & mangled by the autolinker

### LINKED ISSUE #121: Autolink and footnote extensions incorrectly process footnotes with certain letters
Ran across a strange interaction.  With footnotes and autolink enabled, certain footnote names, like with a `w` or an underscore in it, will cause the footnote not to be processed.  Here's an example:

```
The problem seems to be when there's a w or an _ in the footnote anchor.[^w] and [^a] and [^a_a]

[^w]: This won't be rendered.

[^a]: This will be rendered.

[^a_a]: This won't be rendered.
```

using `cmark-gfm --extension footnotes --extension autolink` gives

```
<p>The problem seems to be when there's a w or an _ in the footnote anchor.[^w] and <sup class="footnote-ref"><a href="#fn1" id="fnref1">1</a></sup> and [^a_a]</p>
<section class="footnotes">
<ol>
<li id="fn1">
<p>This will be rendered. <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

Using version `cmark-gfm 0.28.3.gfm.16`

### PR DESCRIPTION
**Pull request by phillmv**
Hello!

This PR closes #121 and helps push https://github.com/github/coding/issues/2251 forward. It supersedes #227.

This PR fixes three different bug fixes in one relatively easy to read PR, combining two tiny changes with a slightly larger one:

- First, [we allow footnotes to be nested](https://github.com/github/cmark-gfm/commit/71e27f25f11c9a34f0532dba459940e1fb5f6316) by changing the order in which footnote definitions are freed.
- Then, [we prevent footnotes from being confused for link references](https://github.com/github/cmark-gfm/commit/1f026ef38bea7636b49c31925ecf95af9bb8834f) by resetting the subject's current state when it erroneously gets advanced.
- Finally, [we correctly read a footnote's reference label, even if it has been broken up into multiple nodes](https://github.com/github/cmark-gfm/commit/bb117ffa7f0dcccdc4d7773f8585ef07e2402f36).

I feel fairly confident functionality wise that this does the trick, but I invite more experienced C hands to tell me how I could improve or better allocate memory 😄.

This PR is a companion to/blocks/see also https://github.com/github/cmark-gfm/pull/230

Cheers,

### CODE REVIEW

File: src/blocks.c [hunk 1]
```diff
@@ -468,7 +468,6 @@ static void process_footnotes(cmark_parser *parser) {
   while ((ev_type = cmark_iter_next(iter)) != CMARK_EVENT_DONE) {
     cur = cmark_iter_get_node(iter);
     if (ev_type == CMARK_EVENT_EXIT && cur->type == CMARK_NODE_FOOTNOTE_DEFINITION) {
-      cmark_node_unlink(cur);
```
Comment (phillmv) [inline src/blocks.c:471]: The changes in this file support [allowing nested foornotes](https://github.com/github/cmark-gfm/pull/229/commits/71e27f25f11c9a34f0532dba459940e1fb5f6316).

We accomplish this by simply changing _when_ we unlink an unused footnote node.

Whereas before, we iterate thru the parser and delete all footnote definitions as we see them

Now we only unlink the footnotes definitions _after we've scanned them for more references_.

File: src/inlines.c [hunk 2]
```diff
@@ -1137,17 +1137,68 @@ static cmark_node *handle_close_bracket(cmark_parser *parser, subject *subj) {
...
+    // look back to the opening '[', and skip ahead to the next character
+    // if we're looking at a '[^' sequence, and there is other text or nodes
+    // after the ^, let's call it a footnote reference.
+    if (literal->data[0] == '^' && (literal->len > 1 || opener->inl_text->next->next)) {
+
+      // Before we got this far, the `handle_close_bracket` function may have
+      // advanced the current state beyond our footnote's actual closing
+      // bracket, ie if it went looking for a `link_label`.
+      // Let's just rewind the subject's position:
+      subj->pos = initial_pos;
```
Comment (phillmv) [inline src/inlines.c:1153]: This one liner fixes a single bug and is best understood in [isolation](https://github.com/github/cmark-gfm/commit/1f026ef38bea7636b49c31925ecf95af9bb8834f) with its [test](https://github.com/github/cmark-gfm/pull/229/commits/740b98704fbd93d1a7dee46077964db7df14263d).

File: src/inlines.c [hunk 3]
```diff
@@ -1137,17 +1137,68 @@ static cmark_node *handle_close_bracket(cmark_parser *parser, subject *subj) {
...
-      inl->start_line = inl->end_line = subj->line;
-      inl->start_column = opener->inl_text->start_column;
-      inl->end_column = subj->pos + subj->column_offset + subj->block_offset;
-      cmark_node_insert_before(opener->inl_text, inl);
-      cmark_node_free(opener->inl_text->next);
+
+    // look back to the opening '[', and skip ahead to the next character
+    // if we're looking at a '[^' sequence, and there is other text or nodes
+    // after the ^, let's call it a footnote reference.
+    if (literal->data[0] == '^' && (literal->len > 1 || opener->inl_text->next->next)) {
```
Comment (phillmv) [inline src/inlines.c:1147]: This changeset tackles footnote reference labels that contain the letter `w`.

When reading this file, consider the [change in isolation](https://github.com/github/cmark-gfm/pull/229/commits/bb117ffa7f0dcccdc4d7773f8585ef07e2402f36) and the [regression test introduced for it](https://github.com/github/cmark-gfm/pull/229/commits/7fa237247371bb3067bcb8fcb4ce74bc95ac04e0).

File: src/inlines.c [hunk 4]
```diff
@@ -1137,17 +1137,68 @@ static cmark_node *handle_close_bracket(cmark_parser *parser, subject *subj) {
...
+      // advanced the current state beyond our footnote's actual closing
+      // bracket, ie if it went looking for a `link_label`.
+      // Let's just rewind the subject's position:
+      subj->pos = initial_pos;
+
+      cmark_node *fnref = make_simple(subj->mem, CMARK_NODE_FOOTNOTE_REFERENCE);
+
+      // the start and end of the footnote ref is the opening and closing brace
+      // i.e. the subject's current position, and the opener's start_column
+      int fnref_end_column = subj->pos + subj->column_offset + subj->block_offset;
```
Comment (nickrolfe) [inline src/inlines.c:1159]: Could this ever overflow with malicious input?

File: src/inlines.c [hunk 5]
```diff
@@ -1137,17 +1137,68 @@ static cmark_node *handle_close_bracket(cmark_parser *parser, subject *subj) {
...
+      // any given node delineates a substring of the line being processed,
+      // with the remainder of the line being pointed to thru its 'literal'
+      // struct member.
+      // here, we copy the literal's pointer, moving it past the '^' character
+      // for a length equal to the size of footnote reference text.
+      // i.e. end_col minus start_col, minus the [ and the ^ characters
+      //
+      // this copies the footnote reference string, even if between the
+      // `opener` and the subject's current position there are other nodes
+      fnref->as.literal = cmark_chunk_dup(literal, 1, (fnref_end_column - fnref_start_column) - 2);
```
Comment (nickrolfe) [inline src/inlines.c:1171]: Can we guarantee that `(fnref_end_column - fnref_start_column) - 2` won't underflow?

File: src/blocks.c [hunk 6]
```diff
@@ -515,8 +514,10 @@ static void process_footnotes(cmark_parser *parser) {
     qsort(map->sorted, map->size, sizeof(cmark_map_entry *), sort_footnote_by_ix);
     for (unsigned int i = 0; i < map->size; ++i) {
       cmark_footnote *footnote = (cmark_footnote *)map->sorted[i];
-      if (!footnote->ix)
+      if (!footnote->ix) {
```
[the remark this answers is not in the document]
Comment (phillmv) [reply src/blocks.c:517]: That's intentional! See footnote spec in `test/extensions.txt`; unused definitions are deleted.

File: src/inlines.c (hunk 4 above)
Comment (phillmv) [reply src/inlines.c:1159]: Great question, I don't think so?

FWIW, this line was adapted from above and represents existing behaviour, see above in deleted lines:

```
inl->end_column = subj->pos + subj->column_offset + subj->block_offset;
```

File: src/inlines.c (hunk 5 above)
Comment (phillmv) [reply src/inlines.c:1171]: in `cmark_chunk_dup`, the last argument is used to set the `cmark_chunk`'s `len` field. 

by the time we get into this part of the function, we are handling a string that looks like: `[^foo]` where the `end_column` is set to index of `]` and the `start_column` is set to the index of '[`.

I am pretty sure `[^]` (an empty footnote reference) will not trigger this code, BUT

would the following be acceptable?

```suggestion
     if((fnref_end_column - fnref_start_column) - 2 >= 0) {
       fnref->as.literal = cmark_chunk_dup(literal, 1, (fnref_end_column - fnref_start_column) - 2);
     } else {
       fnref->as.literal = cmark_chunk_dup(literal, 1, 0);
     }
```

**Comment by philipturnbull** [comment]
I ran the fuzzing harness, `test/cmark-fuzz.c` and it looks like there's a use-after-free when processing footnotes. I collected a few different crashes and they all trigger in `process_emphasis`. For example, an input like:

```
$ hexdump -C github/cmark-gfm/cmark_fuzzer/03c30ed80c1cd8b58ddc91481798ba544d22871b/3c52bca311ed83bf32d8641d0ab014c7ce1fb083/minimized_test_case
00000000  54 66 5b 5e 01 27 6e 6f  5b 5e 27 5d              |Tf[^.'no[^']|
0000000c
```

gives:


```
/work/work842279636/cmark_fuzzer -timeout_exitcode=77 -error_exitcode=78 -rss_limit_mb=1024 -max_len=256 -timeout=1 /work/corpus910357798 -exact_artifact_path=/work/libfuzzer609519651/testcase -dict=/work/work842279636/cmark_fuzzer.dict
Dictionary: 64 entries
INFO: Seed: 3999492952
INFO: Loaded 1 modules   (9519 guards): 9519 [0x9c4600, 0x9cdabc), 
INFO:       49 files found in /work/corpus910357798
INFO: seed corpus: files: 49 min: 5b max: 566b total: 5570b rss: 31Mb
Loaded 1024/1093 files from /work/corpus910357798
=================================================================
==17==ERROR: AddressSanitizer: heap-use-after-free on address 0x60e000257dbc at pc 0x0000005c8b40 bp 0x7ffe2ceb01d0 sp 0x7ffe2ceb01c8
READ of size 4 at 0x60e000257dbc thread T0
SCARINESS: 45 (4-byte-read-heap-use-after-free)
    #0 0x5c8b3f in cmark_chunk_free /src/octofuzz/src/./chunk.h:21:10
    #1 0x5c8b3f in process_emphasis /src/octofuzz/src/inlines.c:691
    #2 0x5c0c8c in handle_close_bracket /src/octofuzz/src/inlines.c:1203:7
    #3 0x5c0c8c in parse_inline /src/octofuzz/src/inlines.c:1397
    #4 0x5c0c8c in cmark_parse_inlines /src/octofuzz/src/inlines.c:1443
    #5 0x5aaefe in process_inlines /src/octofuzz/src/blocks.c:440:9
    #6 0x5aaefe in finalize_document /src/octofuzz/src/blocks.c:632
    #7 0x5aaefe in cmark_parser_finish /src/octofuzz/src/blocks.c:1497
    #8 0x58f2bc in LLVMFuzzerTestOneInput /src/octofuzz/test/cmark-fuzz.c:46:23
    #9 0x53911e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #10 0x537826 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #11 0x53aac6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:587:9
    #12 0x53d367 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:699:5
    #13 0x524d96 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:738:6
    #14 0x5181f8 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #15 0x7f99fa83283f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #16 0x41c058 in _start (/work/work842279636/cmark_fuzzer+0x41c058)
```

<details>

```
0x60e000257dbc is located 124 bytes inside of 152-byte region [0x60e000257d40,0x60e000257dd8)
freed by thread T0 here:
    #0 0x4dcf18 in __interceptor_cfree.localalias.0 /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:76
    #1 0x59f6c7 in S_free_nodes /src/octofuzz/src/node.c:165:5
    #2 0x59f6c7 in cmark_node_free /src/octofuzz/src/node.c:173
    #3 0x5c0c32 in handle_close_bracket /src/octofuzz/src/inlines.c:1198:9
    #4 0x5c0c32 in parse_inline /src/octofuzz/src/inlines.c:1397
    #5 0x5c0c32 in cmark_parse_inlines /src/octofuzz/src/inlines.c:1443
    #6 0x5aaefe in process_inlines /src/octofuzz/src/blocks.c:440:9
    #7 0x5aaefe in finalize_document /src/octofuzz/src/blocks.c:632
    #8 0x5aaefe in cmark_parser_finish /src/octofuzz/src/blocks.c:1497
    #9 0x58f2bc in LLVMFuzzerTestOneInput /src/octofuzz/test/cmark-fuzz.c:46:23
    #10 0x53911e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #11 0x537826 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #12 0x53aac6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:587:9
    #13 0x53d367 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:699:5
    #14 0x524d96 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:738:6
    #15 0x5181f8 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #16 0x7f99fa83283f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

previously allocated by thread T0 here:
    #0 0x4dd2f0 in calloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x59e513 in xcalloc /src/octofuzz/src/cmark.c:18:15
    #2 0x5bca49 in make_literal /src/octofuzz/src/inlines.c:80:33
    #3 0x5bca49 in handle_delim /src/octofuzz/src/inlines.c:548
    #4 0x5bca49 in parse_inline /src/octofuzz/src/inlines.c:1383
    #5 0x5bca49 in cmark_parse_inlines /src/octofuzz/src/inlines.c:1443
    #6 0x5aaefe in process_inlines /src/octofuzz/src/blocks.c:440:9
    #7 0x5aaefe in finalize_document /src/octofuzz/src/blocks.c:632
    #8 0x5aaefe in cmark_parser_finish /src/octofuzz/src/blocks.c:1497
    #9 0x58f2bc in LLVMFuzzerTestOneInput /src/octofuzz/test/cmark-fuzz.c:46:23
    #10 0x53911e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #11 0x537826 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #12 0x53aac6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:587:9
    #13 0x53d367 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:699:5
    #14 0x524d96 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:738:6
    #15 0x5181f8 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #16 0x7f99fa83283f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

SUMMARY: AddressSanitizer: heap-use-after-free /src/octofuzz/src/./chunk.h:21:10 in cmark_chunk_free
Shadow bytes around the buggy address:
  0x0c1c80042f60: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c1c80042f70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1c80042f80: 00 00 00 fa fa fa fa fa fa fa fa fa fd fd fd fd
  0x0c1c80042f90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c1c80042fa0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
=>0x0c1c80042fb0: fd fd fd fd fd fd fd[fd]fd fd fd fa fa fa fa fa
  0x0c1c80042fc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c80042fd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c80042fe0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c80042ff0: fa fa fa fa fa fa fa fa fa fa fa fa fd fd fd fd
  0x0c1c80043000: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17==ABORTING
MS: 3 ChangeByte-CopyPart-PersAutoDict- DE: "freedom planet 2"-; base unit: 1351aa79e45b28e5d15d0bc58ee55443269fedfd
0x54,0x66,0x72,0x65,0x65,0x64,0x6f,0x6d,0x20,0x70,0x6c,0x61,0x6e,0x65,0x74,0x20,0x32,0x2e,0x20,0x49,0x74,0x20,0x68,0x61,0x73,0x20,0x61,0x20,0x63,0x69,0x74,0x61,0x74,0x69,0x6f,0x6e,0x2e,0x5b,0x5e,0x63,0x69,0x74,0x61,0x74,0x69,0x6f,0x6e,0x5d,0xa,0xa,0x5b,0x5e,0x61,0x6e,0x6f,0x74,0x68,0x65,0x72,0x2d,0x63,0x69,0x74,0x61,0x74,0x69,0x69,0x74,0x61,0x74,0x69,0x6f,0x6e,0x2e,0xa,0xa,0x5b,0x5e,0x63,0x69,0x74,0x61,0x74,0x69,0x6f,0x6f,0x6e,0x5d,0x3a,0x20,0x4d,0x79,0x20,0x73,0x65,0x63,0x6f,0x6e,0x64,0x20,0x63,0x69,0x74,0x61,0x74,0x69,0x6f,0x6e,0x2e,0xa,0xa,0x5b,0x5e,0x63,0x69,0x74,0x61,0x74,0x69,0x6f,0x6e,0x5d,0x3a,0x20,0x54,0x68,0x69,0x73,0x20,0x69,0x73,0x20,0x61,0x20,0x6c,0x6f,0x6e,0x67,0x20,0x77,0x69,0x6e,0x64,0x65,0x64,0x20,0x70,0x61,0x72,0x61,0x70,0x67,0x72,0x61,0x70,0x68,0x20,0x74,0x68,0x61,0x74,0x20,0x61,0x6c,0x73,0x6f,0x20,0x68,0x61,0x73,0x20,0x61,0x6e,0x6f,0x74,0x68,0x65,0x72,0x20,0x63,0x69,0x74,0x61,0x74,0x69,0x6f,0x6e,0x2e,0x5b,0x5e,0x61,0x6e,0x6f,0x74,0x68,0x65,0x72,0x2d,0x63,0x69,0x74,0x61,0x74,0x27,0x6f,0x6e,0x5d,0xa,
Tfreedom planet 2. It has a citation.[^citation]\x0a\x0a[^another-citatiitation.\x0a\x0a[^citatioon]: My second citation.\x0a\x0a[^citation]: This is a long winded parapgraph that also has another citation.[^another-citat'on]\x0a
artifact_prefix='./'; Test unit written to /work/libfuzzer609519651/testcase
Base64: VGZyZWVkb20gcGxhbmV0IDIuIEl0IGhhcyBhIGNpdGF0aW9uLlteY2l0YXRpb25dCgpbXmFub3RoZXItY2l0YXRpaXRhdGlvbi4KClteY2l0YXRpb29uXTogTXkgc2Vjb25kIGNpdGF0aW9uLgoKW15jaXRhdGlvbl06IFRoaXMgaXMgYSBsb25nIHdpbmRlZCBwYXJhcGdyYXBoIHRoYXQgYWxzbyBoYXMgYW5vdGhlciBjaXRhdGlvbi5bXmFub3RoZXItY2l0YXQnb25dCg==
```
</details>

which corresponds to `closer->inl_text->as.literal` in:

https://github.com/github/cmark-gfm/blob/993e8692e6e8ea3473022510f058147ca9333133/src/inlines.c#L690-L691

---

Similarly, an input like:

```
$ hexdump -C github/cmark-gfm/cmark_fuzzer/1253ff32ca7acf033392eb4721b44148c3e7aa07/0fba63ca46ff5e2fbab000345cecf182b87d9bd9/minimized_test_case
00000000  54 6f 74 82 bb e3 0a 0a  5b 5e 5f 61 5f 5d        |Tot.....[^_a_]|
0000000e
```

gives:

```
/work/work202675120/cmark_fuzzer -timeout_exitcode=77 -error_exitcode=78 -rss_limit_mb=1024 -max_len=256 -timeout=1 /work/corpus403151970 -exact_artifact_path=/work/libfuzzer395857231/testcase -dict=/work/work202675120/cmark_fuzzer.dict
Dictionary: 64 entries
INFO: Seed: 25948553
INFO: Loaded 1 modules   (9519 guards): 9519 [0x9c4600, 0x9cdabc), 
INFO:       49 files found in /work/corpus403151970
INFO: seed corpus: files: 49 min: 5b max: 566b total: 5570b rss: 31Mb
=================================================================
==18==ERROR: AddressSanitizer: heap-use-after-free on address 0x60e0000085b8 at pc 0x0000005c8b45 bp 0x7ffd5322c850 sp 0x7ffd5322c848
READ of size 4 at 0x60e0000085b8 thread T0
SCARINESS: 45 (4-byte-read-heap-use-after-free)
    #0 0x5c8b44 in S_insert_emph /src/octofuzz/src/inlines.c:734:55
    #1 0x5c8b44 in process_emphasis /src/octofuzz/src/inlines.c:686
    #2 0x5c0c8c in handle_close_bracket /src/octofuzz/src/inlines.c:1203:7
    #3 0x5c0c8c in parse_inline /src/octofuzz/src/inlines.c:1397
    #4 0x5c0c8c in cmark_parse_inlines /src/octofuzz/src/inlines.c:1443
    #5 0x5aaefe in process_inlines /src/octofuzz/src/blocks.c:440:9
    #6 0x5aaefe in finalize_document /src/octofuzz/src/blocks.c:632
    #7 0x5aaefe in cmark_parser_finish /src/octofuzz/src/blocks.c:1497
    #8 0x58f2bc in LLVMFuzzerTestOneInput /src/octofuzz/test/cmark-fuzz.c:46:23
    #9 0x53911e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #10 0x537826 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #11 0x53aac6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:587:9
    #12 0x53d367 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:699:5
    #13 0x524d96 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:738:6
    #14 0x5181f8 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #15 0x7fc7b343f83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #16 0x41c058 in _start (/work/work202675120/cmark_fuzzer+0x41c058)
```

<details>

```
0x60e0000085b8 is located 120 bytes inside of 152-byte region [0x60e000008540,0x60e0000085d8)
freed by thread T0 here:
    #0 0x4dcf18 in __interceptor_cfree.localalias.0 /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:76
    #1 0x59f6c7 in S_free_nodes /src/octofuzz/src/node.c:165:5
    #2 0x59f6c7 in cmark_node_free /src/octofuzz/src/node.c:173
    #3 0x5c0c32 in handle_close_bracket /src/octofuzz/src/inlines.c:1198:9
    #4 0x5c0c32 in parse_inline /src/octofuzz/src/inlines.c:1397
    #5 0x5c0c32 in cmark_parse_inlines /src/octofuzz/src/inlines.c:1443
    #6 0x5aaefe in process_inlines /src/octofuzz/src/blocks.c:440:9
    #7 0x5aaefe in finalize_document /src/octofuzz/src/blocks.c:632
    #8 0x5aaefe in cmark_parser_finish /src/octofuzz/src/blocks.c:1497
    #9 0x58f2bc in LLVMFuzzerTestOneInput /src/octofuzz/test/cmark-fuzz.c:46:23
    #10 0x53911e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #11 0x537826 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #12 0x53aac6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:587:9
    #13 0x53d367 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:699:5
    #14 0x524d96 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:738:6
    #15 0x5181f8 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #16 0x7fc7b343f83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

previously allocated by thread T0 here:
    #0 0x4dd2f0 in calloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x59e513 in xcalloc /src/octofuzz/src/cmark.c:18:15
    #2 0x5bca49 in make_literal /src/octofuzz/src/inlines.c:80:33
    #3 0x5bca49 in handle_delim /src/octofuzz/src/inlines.c:548
    #4 0x5bca49 in parse_inline /src/octofuzz/src/inlines.c:1383
    #5 0x5bca49 in cmark_parse_inlines /src/octofuzz/src/inlines.c:1443
    #6 0x5aaefe in process_inlines /src/octofuzz/src/blocks.c:440:9
    #7 0x5aaefe in finalize_document /src/octofuzz/src/blocks.c:632
    #8 0x5aaefe in cmark_parser_finish /src/octofuzz/src/blocks.c:1497
    #9 0x58f2bc in LLVMFuzzerTestOneInput /src/octofuzz/test/cmark-fuzz.c:46:23
    #10 0x53911e in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #11 0x537826 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #12 0x53aac6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:587:9
    #13 0x53d367 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:699:5
    #14 0x524d96 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:738:6
    #15 0x5181f8 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #16 0x7fc7b343f83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

SUMMARY: AddressSanitizer: heap-use-after-free /src/octofuzz/src/inlines.c:734:55 in S_insert_emph
Shadow bytes around the buggy address:
  0x0c1c7fff9060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff9070: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1c7fff9080: fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff9090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff90a0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
=>0x0c1c7fff90b0: fd fd fd fd fd fd fd[fd]fd fd fd fa fa fa fa fa
  0x0c1c7fff90c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff90d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff90e0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1c7fff90f0: fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1c7fff9100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==18==ABORTING
MS: 2 ShuffleBytes-CrossOver-; base unit: 9bd560bc9f34acce66a6694c78e223a79be55e9c
0x54,0x68,0x69,0x73,0x20,0x69,0x73,0x20,0x73,0x6f,0x6d,0x65,0x20,0x74,0x65,0x78,0x74,0x21,0x5b,0x5e,0x31,0x5d,0x2e,0x20,0x4f,0x74,0x68,0x65,0x72,0x20,0x74,0x65,0x78,0x74,0x2e,0x20,0x72,0x65,0x66,0x65,0x72,0x65,0x6e,0x74,0x5b,0x5e,0x6e,0x6f,0x70,0x65,0x5d,0x2e,0xa,0xa,0xa,0x5b,0x5e,0x6f,0x74,0x68,0x65,0x72,0x2d,0x6e,0x6f,0x74,0x65,0x5d,0x3a,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x6e,0x6f,0x20,0x63,0x6f,0x64,0x65,0x20,0x62,0x6c,0x6f,0x63,0x6b,0x72,0x20,0x74,0x68,0x69,0x6e,0x67,0x5b,0x5e,0x63,0x6f,0x64,0x65,0x62,0x6c,0x6f,0x67,0x6b,0x2d,0x6e,0x6f,0x74,0x48,0xff,0x7,0x65,0x6c,0x6c,0x6f,0x21,0xa,0x7d,0xa,0x7c,0x20,0x5f,0x61,0x62,0x5f,0x20,0x20,0xe3,0x7c,0x63,0x82,0xbb,0xe3,0x83,0xb3,0x29,0x7c,0xa,0x7c,0x20,0x2d,0x2d,0x2d,0x2d,0x2d,0x20,0x7c,0x20,0x6c,0x6c,0x6f,0x21,0xa,0x7d,0xa,0x7c,0x20,0x5f,0x9a,0x6d,0x65,0x6e,0x74,0x73,0x20,0x64,0x6f,0x2a,0x2a,0x5f,0x2e,0x20,0x7c,0x20,0x78,0x20,0x74,0x4a,0xa,0x65,0x5d,0x2e,0xa,0xa,0x54,0x68,0x69,0x73,0x20,0x64,0x6f,0x65,0x73,0x6e,0x27,0x74,0x20,0x68,0x61,0x76,0x65,0x20,0x61,0x20,0x72,0x65,0x66,0x65,0x72,0x65,0x20,0x2d,0x2d,0x2d,0x2d,0xdf,0x3a,0x9a,0x93,0x6e,0x74,0x5b,0x5e,0x6e,0x6f,0x70,0x65,0x5d,0x2e,0xa,0xa,0xa,0x5b,0x5e,0x6f,0x74,0x68,0x65,0x9a,0x6d,0x65,0x6e,0x72,
This is some text![^1]. Other text. referent[^nope].\x0a\x0a\x0a[^other-note]:       no code blockr thing[^codeblogk-notH\xff\x07ello!\x0a}\x0a| _ab_  \xe3|c\x82\xbb\xe3\x83\xb3)|\x0a| ----- | llo!\x0a}\x0a| _\x9aments do**_. | x tJ\x0ae].\x0a\x0aThis doesn't have a refere ----\xdf:\x9a\x93nt[^nope].\x0a\x0a\x0a[^othe\x9amenr
artifact_prefix='./'; Test unit written to /work/libfuzzer395857231/testcase
Base64: VGhpcyBpcyBzb21lIHRleHQhW14xXS4gT3RoZXIgdGV4dC4gcmVmZXJlbnRbXm5vcGVdLgoKClteb3RoZXItbm90ZV06ICAgICAgIG5vIGNvZGUgYmxvY2tyIHRoaW5nW15jb2RlYmxvZ2stbm90SP8HZWxsbyEKfQp8IF9hYl8gION8Y4K744OzKXwKfCAtLS0tLSB8IGxsbyEKfQp8IF+abWVudHMgZG8qKl8uIHwgeCB0SgplXS4KClRoaXMgZG9lc24ndCBoYXZlIGEgcmVmZXJlIC0tLS3fOpqTbnRbXm5vcGVdLgoKClteb3RoZZptZW5y
```

</details>

which corresponds to `opener_inl->as.literal.len` in:

https://github.com/github/cmark-gfm/blob/993e8692e6e8ea3473022510f058147ca9333133/src/inlines.c#L728-L734

---

So it looks like we are incorrectly handling footnotes that themselves contain markdown formatting? Perhaps we shouldn't be calling into `process_emphasis` from `handle_close_bracket`?

**Comment by phillmv** [comment]
Very powerful find, thanks @philipturnbull!

I poked around in this, and I was able to reproduce an infinite hang using `|[^_a_]|` as an input string – even after commenting out `process_emphasis`.

I strongly suspect I am either failing to reset some aspect of the parser state, or there's a dangling pointer elsewhere 🤔 I shall look at it soon.

**Comment by phillmv** [comment]
@philipturnbull I may have figured it out in https://github.com/github/cmark-gfm/pull/229/commits/6e186b307a2addf2d5507de5e35f0d59c7e1c28d ! go figure, trying to free things _before_ calling the next function would lead to shenanigans. I should be able to clean it up, and add a regression test.

I then set up the fuzzer on my end and it found a subtle use-after-free stemming from https://github.com/github/cmark-gfm/pull/229/commits/71e27f25f11c9a34f0532dba459940e1fb5f6316 which I have also figured out! but like with above, shall have to write into a patch another time.

Fuzzers! What a great tool.

**Comment by phillmv** [comment]
I've got the fuzzer running the background trying to dredge up more hits, but afaict I have fixed both issues covered thus far in https://github.com/github/cmark-gfm/pull/229/commits/d3a819ce43d60c26ad0656413e64b50908559cfb and in https://github.com/github/cmark-gfm/pull/229/commits/a1d171ad498757e4fed55aff7fb28e5665af983a 😄.

**Review by brasic — APPROVED** [review]
I'm approving from a functionality perspective with the understanding that fuzzing and review from others has addressed known memory safety issues.

File: src/inlines.c (hunk 3 above)
Comment (bk2204) [reply src/inlines.c:1147]: This is safe if `literal->data` is NUL-terminated, but otherwise, we'll need to check the length first.

File: src/inlines.c (hunk 5 above)
Comment (bk2204) [reply src/inlines.c:1171]: Maybe something like this:

```
if (fn_start_column + 2 >= fnref_end_column)
```

This is a little safer than the subtraction.

**Review by bk2204 — APPROVED** [review]

File: src/inlines.c (hunk 5 above)
Comment (phillmv) [reply src/inlines.c]: 👍 added an underflow check.

File: src/inlines.c (hunk 3 above)
Comment (phillmv) [reply src/inlines.c]: :+1: First, I now check if literal->len has _any_ character.

**Review by bk2204 — APPROVED** [review]

File: src/inlines.c (hunk 2 above)
Comment (waldyrious) [reply src/inlines.c:1153]: > a single bug

For reference, that bug (and a similar fix) had been previously identified in #139.
